name: Update Pyrogram

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install python3-pip
      - name: Install Pyrogram
        run: pip3 install pyrogram
      - name: Check for updates
        run: python3 -c "import pyrogram; print(pyrogram.__version__)"
      - name: Update Pyrogram
        run: pip3 install --upgrade pyrogram
